databases:
  - name: catsalon-db
    databaseName: catsalon
    user: catsalon

services:
  - type: web
    name: catsalon
    runtime: python3
    buildCommand: "pip install -r requirements.txt && python catsaloon/manage.py collectstatic --no-input && python catsaloon/manage.py migrate"
    startCommand: "cd catsaloon && gunicorn catsalon.wsgi:application --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: catsalon-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
